/**
 * CI Quality Gates Check
 * This would be generated by the Debugg CLI during setup
 */

import { debugg } from './src';

// CI Quality Gates Check
async function runCICheck() {
  console.log('🏗️  Running Debugg CI Quality Gates...');

  // Set baseline (in real usage, this would come from previous builds)
  debugg.setCIBaseline(10); // Example: 10 errors in previous build

  // Simulate some errors for testing
  try {
    throw new Error('Test error for CI');
  } catch (error) {
    await debugg.handle(error, { source: 'ci-test' });
  }

  // Run quality gates
  const result = await debugg.runCIQualityGates();

  console.log(result.message);

  if (!result.passed) {
    console.error('❌ CI Quality Gates Failed!');
    process.exit(1);
  } else {
    console.log('✅ CI Quality Gates Passed!');
    process.exit(0);
  }
}

runCICheck().catch(error => {
  console.error('CI Check failed:', error);
  process.exit(1);
});