/**
 * Generate Investor Report
 * This would be generated by the Debugg CLI during setup
 */

import { debugg } from './src';

async function generateReport() {
  console.log('📊 Generating Debugg Investor Report...');
  console.log('======================================\n');

  const report = debugg.generateInvestorReport();
  console.log(report);

  // Also output metrics in JSON format for CI systems
  const metrics = debugg.getInvestorMetrics();
  console.log('\\n📈 JSON Metrics Output:');
  console.log(JSON.stringify(metrics, null, 2));
}

generateReport().catch(console.error);