#!/usr/bin/env node

/**
 * Version Script
 * Runs before npm version command to update version-related files
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const version = args[0];

if (!version) {
  console.error('Error: Version argument required');
  process.exit(1);
}

console.log(`📦 Updating version to ${version}...`);

// Update package.json version is handled by npm
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

console.log(`✓ Package version: ${packageJson.version}`);

// Update version in source if needed
const versionFilePath = path.join(__dirname, '..', 'src', 'version.ts');
const versionContent = `/**
 * Debugg Version
 * Auto-generated by version script
 */

export const VERSION = '${packageJson.version}';
export const BUILD_DATE = '${new Date().toISOString()}';
`;

fs.writeFileSync(versionFilePath, versionContent);
console.log(`✓ Version file updated`);

console.log(`\n✅ Version ${version} ready for release\n`);
